data:
  raw_path: "data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"

split:
  test_size: 0.2
  random_state: 42

model:
  name: "LogisticRegression" # Ahora el interruptor está en Regresión Logística
  
  # --- Parámetros para Random Forest ---
  n_estimators: 100
  max_depth: 10
  
  # --- Parámetros para Regresión Logística ---
  C: 1.0
  max_iter: 1000

paths:
  model_save: "models/model.pkl"